name = "lunacircamonitor"
main = "src/index.ts"
compatibility_date = "2024-11-10"

[triggers]
crons = ["*/10 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "lunacirca-data"
database_id = "c686b317-488f-41f3-bf75-a1510d5bc7a5"
